import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export type VerifyResult = {
  passed: boolean;
  criteria: VerifyCriterion[];
  output: string;
};

export type VerifyCriterion = {
  id: string;
  command: string;
  passed: boolean;
  output: string;
};

export async function runVerifyScript(
  verifyScriptPath: string,
  cwd: string = process.cwd(),
): Promise<VerifyResult> {
  if (!existsSync(verifyScriptPath)) {
    return {
      passed: false,
      criteria: [],
      output: `Verification script not found: ${verifyScriptPath}`,
    };
  }

  const script = readFileSync(verifyScriptPath, "utf-8");
  const lines = script.split("\n");
  const criteria: VerifyCriterion[] = [];
  let output = "";

  const commandLines = lines.filter((line) => {
    const trimmed = line.trim();
    return trimmed && !trimmed.startsWith("#") && !trimmed.startsWith("set ") && !trimmed.startsWith("bash");
  });

  for (let i = 0; i < commandLines.length; i++) {
    const command = commandLines[i];
    const proc = Bun.spawn(["sh", "-c", command], {
      cwd,
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
    ]);
    const exitCode = await proc.exited;
    const combined = (stdout + stderr).trim();
    const passed = exitCode === 0;

    criteria.push({
      id: `c${i + 1}`,
      command,
      passed,
      output: combined.slice(0, 500),
    });

    if (!passed) {
      output += `FAIL [${command}]: ${combined}\n`;
    } else {
      output += `PASS [${command}]\n`;
    }
  }

  return {
    passed: criteria.every((c) => c.passed),
    criteria,
    output,
  };
}

export async function runVerify(
  patchDir: string,
  cwd: string = process.cwd(),
): Promise<VerifyResult> {
  const verifyScriptPath = join(patchDir, "verify.sh");

  if (existsSync(verifyScriptPath)) {
    return await runVerifyScript(verifyScriptPath, cwd);
  }

  const intentPath = join(patchDir, "INTENT.md");
  if (existsSync(intentPath)) {
    const intent = readFileSync(intentPath, "utf-8");
    const match = intent.match(/^verifies_with:\s*(.+)$/m);
    if (match?.[1]) {
      const command = match[1].trim();
      const proc = Bun.spawn(["sh", "-c", command], {
        cwd,
        stdout: "pipe",
        stderr: "pipe",
      });
      const [stdout, stderr] = await Promise.all([
        new Response(proc.stdout).text(),
        new Response(proc.stderr).text(),
      ]);
      const exitCode = await proc.exited;
      const combined = (stdout + stderr).trim();
      return {
        passed: exitCode === 0,
        criteria: [
          {
            id: "verifies_with",
            command,
            passed: exitCode === 0,
            output: combined.slice(0, 500),
          },
        ],
        output: exitCode === 0 ? "PASS" : `FAIL: ${combined}`,
      };
    }
  }

  return {
    passed: true,
    criteria: [],
    output: "No verification script or verifies_with found. Skipping.",
  };
}

export function generateVerifySh(verifiesWith: string, patchId: string): string {
  return `#!/bin/bash
# Verification script for ${patchId}
# Generated by relay-patch. Add patch-specific criteria below.
set -e

# Core: run the project's test suite
${verifiesWith}

# Add patch-specific criteria here:
# Example:
# git diff --quiet upstream/main -- game.ts
# echo "" | bun run index.ts --some-flag | grep -q "expected output"
`;
}
